### ISSUE TITLE
MIssing features

### ISSUE THREAD

**Issue by ed-posinitskiy** [hmarr/pick-dom-element#1]
Hi and big thanks for the component, design looks great with clean and simple interface which is easy to use. I would love to grab this package from one of the projects but  I miss some features:

- Ability to define container boundaries, area where picker is not listening for any mouse movements
- Ability to define selectors to ignore elements on the page, e.g. Ignore navigation bar `.nav`, etc.
- Ability to define selectors to listen to explicitly, e.g. only `a` tags.
- Ability to interrupt event bubbling, i.e. prevent any further action on certain elements in `onHover`. For example if I want to ignore do nothing (no highlighting as well) when I face some reserved elements or so.
- Additional event on mouse out, to have ability to attach my own behaviour on hover, e.g. add class, remove class.

Besides that, please keep going there is really lack of good picker / inspector components in the wild. 
Thank you!

**Comment by hmarr** [comment]
Hi, thanks for your encouraging words!

These sound like sensible feature requests, but I don't have capacity to implement them all myself. Pull requests are welcome, though :-)

> - Ability to define selectors to listen to explicitly, e.g. only a tags.

I actually needed this one myself, so implemented it (via the new `elementFilter` option) in v0.2.0.

Additionally, I'd rather keep feature requests to one-per-issue, so that I can determine interest independently and close them out when they do land. Given this, I'm going to close this issue, but feel free to open new issues if you're still interested in any of the features you mentioned - particularly if you're planning on implementing them!
